# Generated by Django 2.0.9 on 2023-12-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodLine_Logistics', '0002_request_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
