# Generated by Django 2.0.9 on 2024-01-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodLine_Logistics', '0003_auto_20231231_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
